### ISSUE TITLE
Add more informations on Flashing Instructions 

### ISSUE THREAD

**Issue by adremiere-pro** [Vinc2nt/LineageOS_Munch_Releases#1]
Hello, 
I would like to add more information in the flashing instructions in Readme.md to keep il clear for newbies.

| Replace  | by  |
|---|---|
| 5. reboot to recovery now| 5. fastboot reboot recovery|
| 6. wipe data because you are changing rom| 6. Click on "Factory Reset" on Recovery  because you are changing rom |
|7. select adb sideload| 7. Click on "Apply Update" |
|8. adb sideload lineage-20.0-xxxx-UNOFFICIAL-munch.zip| 8. Type "adb sideload lineage-20.0-xxxx-UNOFFICIAL-munch.zip" in you cli|

Thanks / Merci !

**Comment by ad1tyx666** [comment]
Thanks a lot for contributing to the project.
